SeyahatSitesi/SeyahatSitesi/Models/Sınıflar/Oteller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SeyahatSitesi.Models.Sınıflar
{
    public class Oteller
    {
        public int ID { get; set; }
        public string Otel { get; set; }
        public string OtelImage { get; set; }
        public string Acıklama { get; set; }


    }
}

SeyahatSitesi/SeyahatSitesi/Controllers/OtellerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SeyahatSitesi.Models.Sınıflar;

namespace SeyahatSitesi.Controllers
{
    public class OtellerController : Controller
    {
        // GET: Oteller
        Context c = new Context();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult IndexOteller()
        {
            var oteller = c.Otellers.ToList();
            return View(oteller);
        }
     
    }
}

SeyahatSitesi/SeyahatSitesi/Views/Oteller/Index.cshtml
@using SeyahatSitesi.Models.Sınıflar
@model List<Oteller>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_TestLayout1.cshtml";
}


<div class="con-bot">

    <div class="left">
        <div class="bot-left">
            <img src="https://media-cdn.tripadvisor.com/media/photo-s/25/92/53/ba/hotel-facade.jpg" alt="" style="width:300px; height:155px;" />
        </div>
        <div class="left-text">
            <h4> <a href="/Oteller/IndexOteller/">Venedik için oteller</a></h4>
        </div>
    </div>


    <div class="clear"></div>

</div>
@*<div class"content">
    <div class="wrap">
        <div class="wrapper">
            <div class="con-top">
                <div class="left">
                    <div class="bot-left">
                        <img src="https://media-cdn.tripadvisor.com/media/photo-s/25/92/53/ba/hotel-facade.jpg" alt="" style="width:300px; height:155px;" />
                    </div>
                    <div class="left-text">
                        <h4> <a href="/Oteller/IndexOteller/">Venedik için oteller</a></h4>
                    </div>
                </div>
            </div>
            @Html.Action("IndexOteller", "Oteller")
           
        </div>
    </div>
</div>*@

SeyahatSitesi/SeyahatSitesi/Views/Oteller/IndexOteller.cshtml
@using SeyahatSitesi.Models.Sınıflar
@model List<Oteller>
@{
    ViewBag.Title = "IndexOteller";
    Layout = "~/Views/Shared/_TestLayout1.cshtml";
}

<div class="single">
    <div class="container">
        <div class="col-md-8 single-main">
            @foreach (var x in Model)
            {
            <div class="single-grid">
                <center> <img src="@x.OtelImage" alt="" style="margin-bottom:20px" /></center>
                <center> <h4> <a href="#">@x.Otel</a></h4></center>
            </div>
                <br /><br />
            }
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<div class="header_bottom_right_images">

    <div class="slider" cover;*@ style="width:650px;height:370px; display:flex;">
        <ul class="rslides" id="slider1">
            @foreach (var x in Model)
            {
                <li><img src="@x.BlogImage" alt=""></li>
            }

        </ul>
    </div>